### PR TITLE
Update resource test due to the resource parsing changes 

### PR DESCRIPTION
**Pull request by HoundThe**
Update failing tests after parsing changes in https://github.com/avast/retdec/pull/988

### CODE REVIEW

**Review by PeterMatula — CHANGES_REQUESTED** [review]
On two different machines, I get:
```
assert resourceTable['resources'][0]['offset'] == '0xffffffffffffff60'
```
The value I get is `0x561d57d88a70`
here is the full JSON
[7004f68f9142737b2d6c144df6b6d165c5db518e4f06a9fb1a93d1ff129cefa3.log](https://github.com/avast/retdec-regression-tests/files/7037628/7004f68f9142737b2d6c144df6b6d165c5db518e4f06a9fb1a93d1ff129cefa3.log)

**Comment by HoundThe** [comment]
I think I found the reason, it's UB from an uninitialized value in case the offset doesn't point to any section. The source of the problem should be already addressed within this PR https://github.com/avast/retdec/pull/982

**Comment by s3rvac** [comment]
Hi, please, what is the status of the present PR? https://github.com/avast/retdec/pull/982 has been already merged.

**Comment by PeterMatula** [comment]
I was still getting different results on our servers, even though @HoundThe fixed that _"UB from an uninitialized value"_. Since we are not able to run tests on custom `regression-tests` branches in our TC, I decided to merge this to `update_resource_test` branch instead of `master`, create another `update_resource_test` in https://github.com/avast/retdec, create another PR, and see what happens.

**Pull request merged**
